# Dictionary containing fully calibrated live trading values and inferred margins.
# 'market' = Player retail selling value (Tickets)
# 'liquid cost' = Instant wholesale liquidation value (Tickets)
# All Bit frames are accurately locked to 3 market / 2 liquid cost.
# Dojo frames are explicitly set to 0.

FRAME_DB = {
    # ✦ Darkness ✦
    "shadowborn frame": {"market": 68, "liquid cost": 45},
    "crimsonbleed frame": {"market": 60, "liquid cost": 45},
    "phantomblade frame": {"market": 45, "liquid cost": 30},
    "voidspawn frame": {"market": 40, "liquid cost": 35},
    "deathbringer frame": {"market": 70, "liquid cost": 50},

    # ✦ Special ✦
    "maneki neko frame": {"market": 20, "liquid cost": 10},
    "art nouveau frame": {"market": 8, "liquid cost": 5},
    "circus tent frame": {"market": 5, "liquid cost": 2},
    "mirrored energy frame": {"market": 275, "liquid cost": 250},
    "hacker frame": {"market": 180, "liquid cost": 155},
    "easel frame": {"market": 100, "liquid cost": 85},
    "spider lily frame": {"market": 75, "liquid cost": 60},
    "chaosborn frame": {"market": 95, "liquid cost": 70},
    "chrome frame": {"market": 4, "liquid cost": 1},
    "candy land frame": {"market": 3, "liquid cost": 1},
    "illusion frame": {"market": 85, "liquid cost": 71},
    "crystal wings frame": {"market": 180, "liquid cost": 160},
    "noble frame": {"market": 75, "liquid cost": 60},
    "nether frame": {"market": 29, "liquid cost": 15},
    "nova frame": {"market": 70, "liquid cost": 56},
    "cleave frame": {"market": 340, "liquid cost": 310},
    "ashes frame": {"market": 75, "liquid cost": 60},
    "ascendant frame": {"market": 25, "liquid cost": 16},
    "deviation frame": {"market": 55, "liquid cost": 35},
    "divine duality frame": {"market": 75, "liquid cost": 60},
    "royalty frame": {"market": 25, "liquid cost": 20},
    "spellbook frame": {"market": 25, "liquid cost": 20},
    "starshine frame": {"market": 50, "liquid cost": 36},
    "shimmer frame": {"market": 70, "liquid cost": 60},
    "infinity void frame": {"market": 65, "liquid cost": 55},
    "interface frame": {"market": 115, "liquid cost": 90},
    "moon altar frame": {"market": 20, "liquid cost": 10},
    "gazebo frame": {"market": 8, "liquid cost": 4},
    "glinted frame": {"market": 100, "liquid cost": 88},
    "aerial frame": {"market": 30, "liquid cost": 20},
    "lich frame": {"market": 30, "liquid cost": 20},
    "livestream frame": {"market": 73, "liquid cost": 60},
    "the light frame": {"market": 70, "liquid cost": 60},
    "ornate stars frame": {"market": 270, "liquid cost": 255},
    "rebellion frame": {"market": 70, "liquid cost": 60},
    "runic frame": {"market": 50, "liquid cost": 35},
    "djinn lamp frame": {"market": 30, "liquid cost": 20},
    "garden fountain frame": {"market": 12, "liquid cost": 8},
    "butterfly woods frame": {"market": 40, "liquid cost": 35},
    "autumn breeze frame": {"market": 20, "liquid cost": 10},
    "architectura frame": {"market": 3, "liquid cost": 2},
    "arcana frame": {"market": 35, "liquid cost": 20},
    "superhero frame": {"market": 18, "liquid cost": 10},
    "susanoo frame": {"market": 30, "liquid cost": 20},
    "ninjutsu frame": {"market": 20, "liquid cost": 10},
    "pistil suit frame": {"market": 9, "liquid cost": 5},
    "cosmic entity frame": {"market": 45, "liquid cost": 35},
    "budokai frame": {"market": 29, "liquid cost": 15},
    "plasma gun frame": {"market": 25, "liquid cost": 16},
    "sand castle frame": {"market": 15, "liquid cost": 9},
    "fan service frame": {"market": 15, "liquid cost": 11},
    "water vial frame": {"market": 12, "liquid cost": 7},
    "undine frame": {"market": 45, "liquid cost": 35},
    "forbidden frame": {"market": 20, "liquid cost": 15},
    "tao frame": {"market": 10, "liquid cost": 6},
    "arabian nights frame": {"market": 3, "liquid cost": 2},
    "holovortex frame": {"market": 40, "liquid cost": 31},
    "ruined dragon frame": {"market": 5, "liquid cost": 3},
    "earthen frame": {"market": 35, "liquid cost": 20},
    "empyrean frame": {"market": 50, "liquid cost": 35},
    "verdant frame": {"market": 35, "liquid cost": 25},
    "gilded stars frame": {"market": 30, "liquid cost": 16},
    "shattered plumes frame": {"market": 30, "liquid cost": 15},
    "yakuza frame": {"market": 9, "liquid cost": 6},
    "heart of silver frame": {"market": 10, "liquid cost": 6},
    "broken mirror frame": {"market": 30, "liquid cost": 20},
    "zenith frame": {"market": 30, "liquid cost": 21},
    "electrified frame": {"market": 28, "liquid cost": 20},
    "harpstring frame": {"market": 35, "liquid cost": 25},
    "raven frame": {"market": 20, "liquid cost": 10},
    "sea temple frame": {"market": 75, "liquid cost": 60},
    "mermaid frame": {"market": 35, "liquid cost": 25},
    "texting buddy frame": {"market": 28, "liquid cost": 20},
    "azure claw frame": {"market": 25, "liquid cost": 20},
    "banliang frame": {"market": 15, "liquid cost": 8},
    "hanging scrolls frame": {"market": 18, "liquid cost": 11},
    "ice cube frame": {"market": 45, "liquid cost": 31},
    "pumpkin season frame": {"market": 3, "liquid cost": 2},
    "dark cathedral frame": {"market": 4, "liquid cost": 2},
    "manga artist frame": {"market": 25, "liquid cost": 12},
    "martial artist frame": {"market": 9, "liquid cost": 5},
    "mardi gras frame": {"market": 4, "liquid cost": 2},
    "coral reef frame": {"market": 3, "liquid cost": 2},
    "holiday treats frame": {"market": 3, "liquid cost": 2},
    "renaissance frame": {"market": 10, "liquid cost": 5},
    "french maid frame": {"market": 25, "liquid cost": 15},
    "alien alloy frame": {"market": 5, "liquid cost": 2},
    "divinity frame": {"market": 8, "liquid cost": 4},
    "buccaneer frame": {"market": 3, "liquid cost": 2},
    "ming vase frame": {"market": 3, "liquid cost": 2},
    "kitsune frame": {"market": 10, "liquid cost": 7},
    "shadow glass frame": {"market": 10, "liquid cost": 6},
    "omnitech frame": {"market": 3, "liquid cost": 2},
    "pop idol frame": {"market": 20, "liquid cost": 12},
    "karuta boy frame": {"market": 9, "liquid cost": 6},
    "swordsman frame": {"market": 26, "liquid cost": 20},
    "wine nebula frame": {"market": 15, "liquid cost": 8},
    "prototype frame": {"market": 9, "liquid cost": 4},
    "spirit silk frame": {"market": 59, "liquid cost": 50},
    "steampulse frame": {"market": 160, "liquid cost": 145},
    "dragonfruit frame": {"market": 34, "liquid cost": 25},
    "elegance frame": {"market": 7, "liquid cost": 4},
    "destiny frame": {"market": 20, "liquid cost": 15},
    "radiance frame": {"market": 35, "liquid cost": 20},
    "archon frame": {"market": 65, "liquid cost": 50},
    "blaze frame": {"market": 75, "liquid cost": 60},
    "celestial frame": {"market": 85, "liquid cost": 75},
    "ethereal grasp frame": {"market": 45, "liquid cost": 40},
    "demon flame frame": {"market": 48, "liquid cost": 40},
    "night lotus frame": {"market": 26, "liquid cost": 20},
    "scarlet astral frame": {"market": 70, "liquid cost": 55},
    "shoji frame": {"market": 185, "liquid cost": 160},
    "stellar frame": {"market": 80, "liquid cost": 40},
    "ritual frame": {"market": 75, "liquid cost": 50},
    "titan scales frame": {"market": 50, "liquid cost": 25},

    # ✦ Dojo ✦
    "iron rank frame": {"market": 0, "liquid cost": 0},
    "bronze rank frame": {"market": 0, "liquid cost": 0},
    "silver rank frame": {"market": 0, "liquid cost": 0},
    "gold rank frame": {"market": 0, "liquid cost": 0},
    "platinum rank frame": {"market": 0, "liquid cost": 0},
    "diamond rank frame": {"market": 0, "liquid cost": 0},
    "champion rank frame": {"market": 0, "liquid cost": 0},
    "legend rank frame": {"market": 0, "liquid cost": 0},

    # ✦ Monthly / Zodiac ✦
    "year of the rat frame": {"market": 2, "liquid cost": 1},
    "year of the dog frame": {"market": 2, "liquid cost": 1},
    "year of the rooster frame": {"market": 2, "liquid cost": 1},
    "year of the ox frame": {"market": 2, "liquid cost": 1},
    "year of the snake frame": {"market": 2, "liquid cost": 1},
    "year of the dragon frame": {"market": 2, "liquid cost": 1},
    "year of the tiger frame": {"market": 2, "liquid cost": 1},
    "year of the rabbit frame": {"market": 2, "liquid cost": 1},
    "year of the monkey frame": {"market": 2, "liquid cost": 1},
    "year of the horse frame": {"market": 2, "liquid cost": 1},
    "year of the boar frame": {"market": 2, "liquid cost": 1},
    "year of the sheep frame": {"market": 2, "liquid cost": 1},

    # ✦ Carousel ✦
    "wild waters frame": {"market": 0, "liquid cost": 0},
    "higasa frame": {"market": 48, "liquid cost": 40},
    "glory frame": {"market": 50, "liquid cost": 36},
    "rainforest frame": {"market": 55, "liquid cost": 35},
    "explosion frame": {"market": 35, "liquid cost": 34},
    "rainbow galaxy": {"market": 0, "liquid cost": 0},
    "carrara marble frame": {"market": 44, "liquid cost": 30},
    "starry sky frame": {"market": 0, "liquid cost": 0},
    "holy roman frame": {"market": 0, "liquid cost": 0},
    "holy knight frame": {"market": 0, "liquid cost": 0},
    "gothic tower frame": {"market": 0, "liquid cost": 0},
    "brawler frame": {"market": 0, "liquid cost": 0},
    "royal princess frame": {"market": 0, "liquid cost": 0},
    "yin and yang frame": {"market": 0, "liquid cost": 0},
    "fire and ice frame": {"market": 0, "liquid cost": 0},
    "life and death frame": {"market": 25, "liquid cost": 17},
    "fire element frame": {"market": 0, "liquid cost": 0},
    "saloon brawl frame": {"market": 0, "liquid cost": 0},
    "nimbus cloud frame": {"market": 0, "liquid cost": 0},
    "sakura snack frame": {"market": 0, "liquid cost": 0},
    "strawberry dessert frame": {"market": 0, "liquid cost": 0},
    "desert rose frame": {"market": 0, "liquid cost": 0},
    "sushi buffet frame": {"market": 0, "liquid cost": 0},
    "simulation frame": {"market": 50, "liquid cost": 35},
    "noxious frame": {"market": 21, "liquid cost": 14},
    "cat cafe frame": {"market": 0, "liquid cost": 0},
    "japanese alley frame": {"market": 0, "liquid cost": 0},
    "coffee shop frame": {"market": 0, "liquid cost": 0},
    "chess frame": {"market": 0, "liquid cost": 0},
    "chefs kitchen frame": {"market": 0, "liquid cost": 0},
    "moon kingdom frame": {"market": 0, "liquid cost": 0},
    "magitor frame": {"market": 45, "liquid cost": 35},
    "mahou frame": {"market": 26, "liquid cost": 18},
    "stained glass frame": {"market": 0, "liquid cost": 0},
    "stage showman frame": {"market": 0, "liquid cost": 0},
    "prison break frame": {"market": 0, "liquid cost": 0},
    "wanted frame": {"market": 60, "liquid cost": 42},
    "butler frame": {"market": 45, "liquid cost": 36},
    "kimono frame": {"market": 50, "liquid cost": 25},
    "mad tea party frame": {"market": 0, "liquid cost": 0},
    "classroom frame": {"market": 0, "liquid cost": 0},
    "bookworm frame": {"market": 0, "liquid cost": 0},
    "her bedroom frame": {"market": 0, "liquid cost": 0},
    "jamboree frame": {"market": 0, "liquid cost": 0},
    "white tiara frame": {"market": 30, "liquid cost": 15},
    "black tiara frame": {"market": 0, "liquid cost": 0},
    "dark iron frame": {"market": 30, "liquid cost": 15},
    "dragon balls frame": {"market": 0, "liquid cost": 0},
    "aztec jungle frame": {"market": 0, "liquid cost": 0},
    "garden snake frame": {"market": 0, "liquid cost": 0},
    "serpent temple frame": {"market": 0, "liquid cost": 0},
    "bridesmaid frame": {"market": 0, "liquid cost": 0},
    "groomsman frame": {"market": 0, "liquid cost": 0},
    "frostborn frame": {"market": 36, "liquid cost": 25},
    "arcade machine frame": {"market": 0, "liquid cost": 0},
    "jewelry box frame": {"market": 0, "liquid cost": 0},
    "jurassic frame": {"market": 0, "liquid cost": 0},
    "rabbit hole frame": {"market": 0, "liquid cost": 0},
    "vizier frame": {"market": 0, "liquid cost": 0},
    "rusty fortress frame": {"market": 0, "liquid cost": 0},
    "vaporwave frame": {"market": 0, "liquid cost": 0},
    "volleyball frame": {"market": 0, "liquid cost": 0},
    "poolside frame": {"market": 0, "liquid cost": 0},
    "molten frame": {"market": 50, "liquid cost": 35},
    "panda frame": {"market": 0, "liquid cost": 0},
    "slums frame": {"market": 0, "liquid cost": 0},
    "frosted glass frame": {"market": 50, "liquid cost": 25},
    "mobile suit frame": {"market": 0, "liquid cost": 0},
    "stacked deck frame": {"market": 0, "liquid cost": 0},
    "kintsugi frame": {"market": 0, "liquid cost": 0},
    "astrolabe frame": {"market": 0, "liquid cost": 0},
    "constellations frame": {"market": 0, "liquid cost": 0},
    "witch altar frame": {"market": 0, "liquid cost": 0},
    "geode frame": {"market": 0, "liquid cost": 0},
    "tarot card frame": {"market": 59, "liquid cost": 31},
    "tatami frame": {"market": 0, "liquid cost": 0},
    "tetsuo frame": {"market": 0, "liquid cost": 0},
    "casino frame": {"market": 0, "liquid cost": 0},
    "case files frame": {"market": 0, "liquid cost": 0},
    "hannya frame": {"market": 40, "liquid cost": 20},
    "starter town frame": {"market": 55, "liquid cost": 38},
    "archangel frame": {"market": 30, "liquid cost": 15},
    "electrocell frame": {"market": 0, "liquid cost": 0},
    "nightmare frame": {"market": 0, "liquid cost": 0},
    "pastel castle frame": {"market": 0, "liquid cost": 0},
    "exotic birds frame": {"market": 0, "liquid cost": 0},
    "alchemist frame": {"market": 0, "liquid cost": 0},
    "origami frame": {"market": 25, "liquid cost": 15},
    "gothic ornament frame": {"market": 0, "liquid cost": 0},
    "petals frame": {"market": 55, "liquid cost": 35},
    "corrupted titanium frame": {"market": 0, "liquid cost": 0},
    "heraldic frame": {"market": 0, "liquid cost": 0},
    "leather belt frame": {"market": 0, "liquid cost": 0},
    "samurai frame": {"market": 55, "liquid cost": 28},
    "crime scene frame": {"market": 0, "liquid cost": 0},
    "tomb relic frame": {"market": 0, "liquid cost": 0},
    "blueprint frame": {"market": 0, "liquid cost": 0},
    "shining diamond frame": {"market": 40, "liquid cost": 28},
    "grove druid frame": {"market": 0, "liquid cost": 0},

    # ✦ Event - Spring ✦
    "rustic springtide frame": {"market": 3, "liquid cost": 2},
    "ostara frame": {"market": 9, "liquid cost": 6},
    "spring crafts frame": {"market": 0, "liquid cost": 0},
    "springtide treats frame": {"market": 0, "liquid cost": 0},
    "springtide vibes frame": {"market": 0, "liquid cost": 0},
    "bunny paws frame": {"market": 40, "liquid cost": 20},
    "spring lilies frame": {"market": 0, "liquid cost": 0},
    "chocolate bunny frame": {"market": 0, "liquid cost": 0},
    "springtide timber frame": {"market": 3, "liquid cost": 3},
    "spring hatchling frame": {"market": 4, "liquid cost": 2},
    "tranquil blossom frame": {"market": 60, "liquid cost": 40},
    "spring breeze frame": {"market": 60, "liquid cost": 50},
    "rose knight frame": {"market": 50, "liquid cost": 35},
    "enchanted garden frame": {"market": 0, "liquid cost": 0},
    "spring glimmer frame": {"market": 0, "liquid cost": 0},
    "midnight bloom frame": {"market": 35, "liquid cost": 18},
    "spring whimsy frame": {"market": 5, "liquid cost": 0},
    "flowerbuds frame": {"market": 70, "liquid cost": 50},
    "spring rain frame": {"market": 0, "liquid cost": 0},
    "springtide serenity frame": {"market": 31, "liquid cost": 30},
    "elven blossom frame": {"market": 45, "liquid cost": 30},
    "sheep puff frame": {"market": 0, "liquid cost": 0},
    "bunny bliss frame": {"market": 5, "liquid cost": 3},
    "valley elegance frame": {"market": 3, "liquid cost": 2},
    "midnight petal frame": {"market": 27, "liquid cost": 18},
    "moonlit bloom frame": {"market": 27, "liquid cost": 18},
    "luminous wings frame": {"market": 27, "liquid cost": 18},
    "fragrant bloom frame": {"market": 27, "liquid cost": 18},
    "golden nectar frame": {"market": 5, "liquid cost": 2},
    "chocolate drizzle frame": {"market": 2, "liquid cost": 1},

    # ✦ Event - Summer ✦
    "park picnic frame": {"market": 0, "liquid cost": 0},
    "island luau frame": {"market": 0, "liquid cost": 0},
    "beach towel frame": {"market": 4, "liquid cost": 2},
    "ice cream parlor frame": {"market": 0, "liquid cost": 0},
    "solisfair sip frame": {"market": 0, "liquid cost": 0},
    "tropical flame frame": {"market": 0, "liquid cost": 0},
    "solisfair stand frame": {"market": 3, "liquid cost": 3},
    "summer splash frame": {"market": 28, "liquid cost": 20},
    "island grotto frame": {"market": 3, "liquid cost": 2},
    "night festival frame": {"market": 28, "liquid cost": 20},
    "apollo frame": {"market": 35, "liquid cost": 18},
    "oceanic frame": {"market": 4, "liquid cost": 2},
    "lifeguard frame": {"market": 3, "liquid cost": 2},
    "suncatcher frame": {"market": 30, "liquid cost": 20},
    "ripple frame": {"market": 45, "liquid cost": 35},
    "fishing trip frame": {"market": 3, "liquid cost": 2},
    "solisfair swirl frame": {"market": 15, "liquid cost": 8},
    "macaw chief frame": {"market": 3, "liquid cost": 2},
    "warm rain frame": {"market": 25, "liquid cost": 15},
    "karuta vice frame": {"market": 3, "liquid cost": 2},

    # ✦ Event - Halloween ✦
    "halloween porch frame": {"market": 30, "liquid cost": 20},
    "orb weaver frame": {"market": 35, "liquid cost": 20},
    "haunted cemetery frame": {"market": 0, "liquid cost": 0},
    "mad scientist frame": {"market": 0, "liquid cost": 0},
    "bone construct frame": {"market": 18, "liquid cost": 10},
    "cursed place frame": {"market": 18, "liquid cost": 10},
    "witchs broom frame": {"market": 0, "liquid cost": 0},
    "tpd frame": {"market": 7, "liquid cost": 4},
    "living dead frame": {"market": 0, "liquid cost": 0},
    "pumpkin king frame": {"market": 9, "liquid cost": 6},
    "sealed graveyard frame": {"market": 45, "liquid cost": 22},
    "monsterific frame": {"market": 10, "liquid cost": 6},
    "caged essence frame": {"market": 13, "liquid cost": 8},
    "witchs brew frame": {"market": 5, "liquid cost": 3},
    "boneslasher frame": {"market": 26, "liquid cost": 25},
    "undead domain frame": {"market": 9, "liquid cost": 6},
    "bloodmoon bite frame": {"market": 40, "liquid cost": 30},
    "gothic cloak frame": {"market": 0, "liquid cost": 0},
    "spider queen frame": {"market": 85, "liquid cost": 70},
    "nightwalker frame": {"market": 20, "liquid cost": 10},
    "phantoms lament frame": {"market": 17, "liquid cost": 10},
    "black widow frame": {"market": 5, "liquid cost": 3},
    "cursed relics frame": {"market": 14, "liquid cost": 10},
    "haunted harvest frame": {"market": 5, "liquid cost": 3},
    "eldritch frame": {"market": 20, "liquid cost": 12},
    "grasping shadows frame": {"market": 0, "liquid cost": 0},
    "silent burial frame": {"market": 20, "liquid cost": 10},
    "haunted thicket frame": {"market": 0, "liquid cost": 0},
    "sinister reach frame": {"market": 30, "liquid cost": 15},
    "magic library frame": {"market": 4, "liquid cost": 2},

    # ✦ Event - Festivus ✦
    "snow tree frame": {"market": 40, "liquid cost": 20},
    "mistletoe season frame": {"market": 35, "liquid cost": 18},
    "nutcracker frame": {"market": 0, "liquid cost": 0},
    "festivus presents frame": {"market": 20, "liquid cost": 10},
    "winter campfire frame": {"market": 0, "liquid cost": 0},
    "festivus park frame": {"market": 15, "liquid cost": 8},
    "festivus freeze frame": {"market": 102, "liquid cost": 65},
    "festive dinner frame": {"market": 0, "liquid cost": 0},
    "festivus night frame": {"market": 18, "liquid cost": 10},
    "present time frame": {"market": 43, "liquid cost": 22},
    "snowdrop frame": {"market": 0, "liquid cost": 0},
    "festivus lights frame": {"market": 5, "liquid cost": 3},
    "snowed in frame": {"market": 4, "liquid cost": 2},
    "ornamental frame": {"market": 0, "liquid cost": 0},
    "wrapped frame": {"market": 8, "liquid cost": 5},
    "peppermint frame": {"market": 23, "liquid cost": 21},
    "frostwood frame": {"market": 0, "liquid cost": 0},
    "shortbread frame": {"market": 0, "liquid cost": 0},
    "icicle frame": {"market": 85, "liquid cost": 75},
    "snow day frame": {"market": 0, "liquid cost": 0},
    "festivity frame": {"market": 6, "liquid cost": 4},
    "gingerbake frame": {"market": 3, "liquid cost": 2},
    "snowfire frame": {"market": 20, "liquid cost": 15},
    "chocomint frame": {"market": 3, "liquid cost": 2},
    "jingle bells frame": {"market": 3, "liquid cost": 2},
    "boreal sparkles frame": {"market": 10, "liquid cost": 7},
    "cris wind frame": {"market": 40, "liquid cost": 20},
    "enchanted star frame": {"market": 15, "liquid cost": 8},
    "runic frost frame": {"market": 28, "liquid cost": 20},
    "warm mantle frame": {"market": 4, "liquid cost": 2},

    # ✦ Event - Valentines ✦
    "cupids lock frame": {"market": 15, "liquid cost": 8},
    "cupids arrow frame": {"market": 15, "liquid cost": 8},
    "polished locket frame": {"market": 0, "liquid cost": 0},
    "crystalline locket frame": {"market": 0, "liquid cost": 0},
    "sweetheart frame": {"market": 85, "liquid cost": 70},
    "heartbreak frame": {"market": 50, "liquid cost": 35},
    "wife frame": {"market": 75, "liquid cost": 60},
    "husband frame": {"market": 28, "liquid cost": 20},
    "primrose frame": {"market": 40, "liquid cost": 25},
    "grimrose frame": {"market": 45, "liquid cost": 30},
    "sanguine wisps frame": {"market": 16, "liquid cost": 10},
    "pastel wisps frame": {"market": 20, "liquid cost": 10},

    # ✦ Anniversary ✦
    "karuta anniversary 2021 frame": {"market": 15, "liquid cost": 8},
    "karuta anniversary 2022 frame": {"market": 0, "liquid cost": 0},
    "karuta anniversary 2023 frame": {"market": 9, "liquid cost": 6},
    "karuta anniversary 2024 frame": {"market": 3, "liquid cost": 2},
    "karuta anniversary 2025 frame": {"market": 3, "liquid cost": 2},
    "karuta anniversary 2026 frame": {"market": 20, "liquid cost": 12},

    # ✦ Bits ✦
    "brass frame": {"market": 3, "liquid cost": 2},
    "fortress frame": {"market": 3, "liquid cost": 2},
    "beachside frame": {"market": 3, "liquid cost": 2},
    "volcanic frame": {"market": 3, "liquid cost": 2},
    "cherry blossom frame": {"market": 3, "liquid cost": 2},
    "spirit flame frame": {"market": 3, "liquid cost": 2},
    "night crow frame": {"market": 3, "liquid cost": 2},
    "crystal mines frame": {"market": 3, "liquid cost": 2},
    "submarine frame": {"market": 3, "liquid cost": 2},
    "pirate voyage frame": {"market": 3, "liquid cost": 2},
    "kominka frame": {"market": 3, "liquid cost": 2},
    "magus frame": {"market": 3, "liquid cost": 2},
    "magitek frame": {"market": 3, "liquid cost": 2},
    "snowlands frame": {"market": 3, "liquid cost": 2},
    "ice cream sundae frame": {"market": 3, "liquid cost": 2},
    "dragon hunt frame": {"market": 3, "liquid cost": 2},
    "patchwork frame": {"market": 3, "liquid cost": 2},
    "venice carnival frame": {"market": 3, "liquid cost": 2},
    "robotic frame": {"market": 3, "liquid cost": 2},
    "frills frame": {"market": 3, "liquid cost": 2},
    "fuselage frame": {"market": 3, "liquid cost": 2},
    "rozen frame": {"market": 3, "liquid cost": 2},
    "smithy forge frame": {"market": 3, "liquid cost": 2},
    "watermelon juice frame": {"market": 3, "liquid cost": 2},
    "faerie forest frame": {"market": 3, "liquid cost": 2},
    "autumn view frame": {"market": 3, "liquid cost": 2},
    "edo furin frame": {"market": 3, "liquid cost": 2},
    "barbecue frame": {"market": 3, "liquid cost": 2},
    "whirlpool frame": {"market": 3, "liquid cost": 2},
    "bubble bath frame": {"market": 3, "liquid cost": 2},
    "spaceship frame": {"market": 3, "liquid cost": 2},
    "wild west frame": {"market": 3, "liquid cost": 2},
    "archery frame": {"market": 3, "liquid cost": 2},
    "tree frog frame": {"market": 3, "liquid cost": 2},
    "scimitar fight frame": {"market": 3, "liquid cost": 2},
    "bamboo stalks frame": {"market": 3, "liquid cost": 2},
    "chocolate orange frame": {"market": 3, "liquid cost": 2},
    "tribal chief frame": {"market": 3, "liquid cost": 2},
    "abandoned church frame": {"market": 3, "liquid cost": 2},
    "long hair frame": {"market": 3, "liquid cost": 2},
    "water element frame": {"market": 3, "liquid cost": 2},
    "carved stone frame": {"market": 3, "liquid cost": 2},
    "beauty frame": {"market": 3, "liquid cost": 2},
    "carnations frame": {"market": 3, "liquid cost": 2},
    "baroque frame": {"market": 3, "liquid cost": 2},
    "musical notes frame": {"market": 3, "liquid cost": 2},
    "winners podium frame": {"market": 3, "liquid cost": 2},
    "manticore frame": {"market": 3, "liquid cost": 2},
    "tipsy frame": {"market": 3, "liquid cost": 2},
    "nordic frame": {"market": 3, "liquid cost": 2},
    "shiba inu frame": {"market": 3, "liquid cost": 2},
    "toy mecha frame": {"market": 3, "liquid cost": 2},
    "bubble tea frame": {"market": 3, "liquid cost": 2},
    "morning dew frame": {"market": 3, "liquid cost": 2},
    "nurses office frame": {"market": 3, "liquid cost": 2},
    "honeycomb frame": {"market": 3, "liquid cost": 2},
    "magical girl frame": {"market": 3, "liquid cost": 2},
    "tetromino frame": {"market": 3, "liquid cost": 2},
    "flying dragon frame": {"market": 3, "liquid cost": 2},
    "gaming chair frame": {"market": 3, "liquid cost": 2},
    "tanglung frame": {"market": 3, "liquid cost": 2},
    "pastel geometry frame": {"market": 3, "liquid cost": 2},
    "lighthouse storm frame": {"market": 3, "liquid cost": 2},
    "chopsticks frame": {"market": 3, "liquid cost": 2},
    "haunted stone frame": {"market": 3, "liquid cost": 2},
    "kawaii bento frame": {"market": 3, "liquid cost": 2},
    "pocket pet frame": {"market": 3, "liquid cost": 2},
    "jade cherrywood frame": {"market": 3, "liquid cost": 2},
    "pharaoh frame": {"market": 3, "liquid cost": 2},
    "shisa frame": {"market": 3, "liquid cost": 2},
    "butterfly garden frame": {"market": 3, "liquid cost": 2},
    "labpunk frame": {"market": 3, "liquid cost": 2},
    "wizards hut frame": {"market": 3, "liquid cost": 2},
    "flame temple frame": {"market": 3, "liquid cost": 2},
    "night ooze frame": {"market": 3, "liquid cost": 2},
    "prehistoric frame": {"market": 3, "liquid cost": 2},
    "kraken frame": {"market": 3, "liquid cost": 2},
    "bewitched parchment frame": {"market": 3, "liquid cost": 2},
    "malice tree frame": {"market": 3, "liquid cost": 2},
    "reclaimed by nature frame": {"market": 3, "liquid cost": 2},
    "cherry berry frame": {"market": 3, "liquid cost": 2},
    "seamster frame": {"market": 3, "liquid cost": 2}
}