# Dictionary containing fully calibrated live trading values and inferred margins.
# 'market' = Player retail selling value (Tickets)
# 'liquid cost' = Instant wholesale liquidation value (Tickets)
# 'type' = The category or origin of the frame

FRAME_DB = {
    # ✦ Darkness ✦
    "shadowborn frame": {"market": 68, "liquid cost": 45, "type": "Darkness"},
    "crimsonbleed frame": {"market": 60, "liquid cost": 45, "type": "Darkness"},
    "phantomblade frame": {"market": 45, "liquid cost": 30, "type": "Darkness"},
    "voidspawn frame": {"market": 40, "liquid cost": 35, "type": "Darkness"},
    "deathbringer frame": {"market": 70, "liquid cost": 50, "type": "Darkness"},

    # ✦ Special ✦
    "maneki neko frame": {"market": 20, "liquid cost": 10, "type": "Special"},
    "art nouveau frame": {"market": 8, "liquid cost": 5, "type": "Special"},
    "circus tent frame": {"market": 5, "liquid cost": 2, "type": "Special"},
    "mirrored energy frame": {"market": 275, "liquid cost": 250, "type": "Special"},
    "hacker frame": {"market": 180, "liquid cost": 155, "type": "Special"},
    "easel frame": {"market": 100, "liquid cost": 85, "type": "Special"},
    "spider lily frame": {"market": 75, "liquid cost": 60, "type": "Special"},
    "chaosborn frame": {"market": 95, "liquid cost": 70, "type": "Special"},
    "chrome frame": {"market": 4, "liquid cost": 1, "type": "Special"},
    "candy land frame": {"market": 3, "liquid cost": 1, "type": "Special"},
    "illusion frame": {"market": 85, "liquid cost": 71, "type": "Special"},
    "crystal wings frame": {"market": 180, "liquid cost": 160, "type": "Special"},
    "noble frame": {"market": 75, "liquid cost": 60, "type": "Special"},
    "nether frame": {"market": 29, "liquid cost": 15, "type": "Special"},
    "nova frame": {"market": 70, "liquid cost": 56, "type": "Special"},
    "cleave frame": {"market": 340, "liquid cost": 310, "type": "Special"},
    "ashes frame": {"market": 75, "liquid cost": 60, "type": "Special"},
    "ascendant frame": {"market": 25, "liquid cost": 16, "type": "Special"},
    "deviation frame": {"market": 55, "liquid cost": 35, "type": "Special"},
    "divine duality frame": {"market": 75, "liquid cost": 60, "type": "Special"},
    "royalty frame": {"market": 25, "liquid cost": 20, "type": "Special"},
    "spellbook frame": {"market": 25, "liquid cost": 20, "type": "Special"},
    "starshine frame": {"market": 50, "liquid cost": 36, "type": "Special"},
    "shimmer frame": {"market": 70, "liquid cost": 60, "type": "Special"},
    "infinity void frame": {"market": 65, "liquid cost": 55, "type": "Special"},
    "interface frame": {"market": 115, "liquid cost": 90, "type": "Special"},
    "moon altar frame": {"market": 20, "liquid cost": 10, "type": "Special"},
    "gazebo frame": {"market": 8, "liquid cost": 4, "type": "Special"},
    "glinted frame": {"market": 100, "liquid cost": 88, "type": "Special"},
    "aerial frame": {"market": 30, "liquid cost": 20, "type": "Special"},
    "lich frame": {"market": 30, "liquid cost": 20, "type": "Special"},
    "livestream frame": {"market": 73, "liquid cost": 60, "type": "Special"},
    "the light frame": {"market": 70, "liquid cost": 60, "type": "Special"},
    "ornate stars frame": {"market": 270, "liquid cost": 255, "type": "Special"},
    "rebellion frame": {"market": 70, "liquid cost": 60, "type": "Special"},
    "runic frame": {"market": 50, "liquid cost": 35, "type": "Special"},
    "djinn lamp frame": {"market": 30, "liquid cost": 20, "type": "Special"},
    "garden fountain frame": {"market": 12, "liquid cost": 8, "type": "Special"},
    "butterfly woods frame": {"market": 40, "liquid cost": 35, "type": "Special"},
    "autumn breeze frame": {"market": 20, "liquid cost": 10, "type": "Special"},
    "architectura frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "arcana frame": {"market": 35, "liquid cost": 20, "type": "Special"},
    "superhero frame": {"market": 18, "liquid cost": 10, "type": "Special"},
    "susanoo frame": {"market": 30, "liquid cost": 20, "type": "Special"},
    "ninjutsu frame": {"market": 20, "liquid cost": 10, "type": "Special"},
    "pistil suit frame": {"market": 9, "liquid cost": 5, "type": "Special"},
    "cosmic entity frame": {"market": 45, "liquid cost": 35, "type": "Special"},
    "budokai frame": {"market": 29, "liquid cost": 15, "type": "Special"},
    "plasma gun frame": {"market": 25, "liquid cost": 16, "type": "Special"},
    "sand castle frame": {"market": 15, "liquid cost": 9, "type": "Special"},
    "fan service frame": {"market": 15, "liquid cost": 11, "type": "Special"},
    "water vial frame": {"market": 12, "liquid cost": 7, "type": "Special"},
    "undine frame": {"market": 45, "liquid cost": 35, "type": "Special"},
    "forbidden frame": {"market": 20, "liquid cost": 15, "type": "Special"},
    "tao frame": {"market": 10, "liquid cost": 6, "type": "Special"},
    "arabian nights frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "holovortex frame": {"market": 40, "liquid cost": 31, "type": "Special"},
    "ruined dragon frame": {"market": 5, "liquid cost": 3, "type": "Special"},
    "earthen frame": {"market": 35, "liquid cost": 20, "type": "Special"},
    "empyrean frame": {"market": 50, "liquid cost": 35, "type": "Special"},
    "verdant frame": {"market": 35, "liquid cost": 25, "type": "Special"},
    "gilded stars frame": {"market": 30, "liquid cost": 16, "type": "Special"},
    "shattered plumes frame": {"market": 30, "liquid cost": 15, "type": "Special"},
    "yakuza frame": {"market": 9, "liquid cost": 6, "type": "Special"},
    "heart of silver frame": {"market": 10, "liquid cost": 6, "type": "Special"},
    "broken mirror frame": {"market": 30, "liquid cost": 20, "type": "Special"},
    "zenith frame": {"market": 30, "liquid cost": 21, "type": "Special"},
    "electrified frame": {"market": 28, "liquid cost": 20, "type": "Special"},
    "harpstring frame": {"market": 35, "liquid cost": 25, "type": "Special"},
    "raven frame": {"market": 20, "liquid cost": 10, "type": "Special"},
    "sea temple frame": {"market": 75, "liquid cost": 60, "type": "Special"},
    "mermaid frame": {"market": 35, "liquid cost": 25, "type": "Special"},
    "texting buddy frame": {"market": 28, "liquid cost": 20, "type": "Special"},
    "azure claw frame": {"market": 25, "liquid cost": 20, "type": "Special"},
    "banliang frame": {"market": 15, "liquid cost": 8, "type": "Special"},
    "hanging scrolls frame": {"market": 18, "liquid cost": 11, "type": "Special"},
    "ice cube frame": {"market": 45, "liquid cost": 31, "type": "Special"},
    "pumpkin season frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "dark cathedral frame": {"market": 4, "liquid cost": 2, "type": "Special"},
    "manga artist frame": {"market": 25, "liquid cost": 12, "type": "Special"},
    "martial artist frame": {"market": 9, "liquid cost": 5, "type": "Special"},
    "mardi gras frame": {"market": 4, "liquid cost": 2, "type": "Special"},
    "coral reef frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "holiday treats frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "renaissance frame": {"market": 10, "liquid cost": 5, "type": "Special"},
    "french maid frame": {"market": 25, "liquid cost": 15, "type": "Special"},
    "alien alloy frame": {"market": 5, "liquid cost": 2, "type": "Special"},
    "divinity frame": {"market": 8, "liquid cost": 4, "type": "Special"},
    "buccaneer frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "ming vase frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "kitsune frame": {"market": 10, "liquid cost": 7, "type": "Special"},
    "shadow glass frame": {"market": 10, "liquid cost": 6, "type": "Special"},
    "omnitech frame": {"market": 3, "liquid cost": 2, "type": "Special"},
    "pop idol frame": {"market": 20, "liquid cost": 12, "type": "Special"},
    "karuta boy frame": {"market": 9, "liquid cost": 6, "type": "Special"},
    "swordsman frame": {"market": 26, "liquid cost": 20, "type": "Special"},
    "wine nebula frame": {"market": 15, "liquid cost": 8, "type": "Special"},
    "prototype frame": {"market": 9, "liquid cost": 4, "type": "Special"},
    "spirit silk frame": {"market": 59, "liquid cost": 50, "type": "Special"},
    "steampulse frame": {"market": 160, "liquid cost": 145, "type": "Special"},
    "dragonfruit frame": {"market": 34, "liquid cost": 25, "type": "Special"},
    "elegance frame": {"market": 7, "liquid cost": 4, "type": "Special"},
    "destiny frame": {"market": 20, "liquid cost": 15, "type": "Special"},
    "radiance frame": {"market": 35, "liquid cost": 20, "type": "Special"},
    "archon frame": {"market": 65, "liquid cost": 50, "type": "Special"},
    "blaze frame": {"market": 75, "liquid cost": 60, "type": "Special"},
    "celestial frame": {"market": 85, "liquid cost": 70, "type": "Special"},
    "ethereal grasp frame": {"market": 50, "liquid cost": 40, "type": "Special"},
    "demon flame frame": {"market": 62, "liquid cost": 50, "type": "Special"},
    "night lotus frame": {"market": 35, "liquid cost": 25, "type": "Special"},
    "scarlet astral frame": {"market": 55, "liquid cost": 40, "type": "Special"},
    "shoji frame": {"market": 190, "liquid cost": 160, "type": "Special"},
    "stellar frame": {"market": 70, "liquid cost": 60, "type": "Special"},
    "ritual frame": {"market": 65, "liquid cost": 50, "type": "Special"},
    "titan scales frame": {"market": 50, "liquid cost": 40, "type": "Special"},

    # ✦ Dojo ✦
    "iron rank frame": {"market": 3, "liquid cost": 2, "type": "Dojo"},
    "bronze rank frame": {"market": 3, "liquid cost": 2, "type": "Dojo"},
    "silver rank frame": {"market": 3, "liquid cost": 2, "type": "Dojo"},
    "gold rank frame": {"market": 5, "liquid cost": 2, "type": "Dojo"},
    "platinum rank frame": {"market": 7, "liquid cost": 3, "type": "Dojo"},
    "diamond rank frame": {"market": 12, "liquid cost": 5, "type": "Dojo"},
    "champion rank frame": {"market": 40, "liquid cost": 30, "type": "Dojo"},
    "legend rank frame": {"market": 1000, "liquid cost": 700, "type": "Dojo"},

    # ✦ Monthly / Zodiac ✦
    "year of the rat frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the dog frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the rooster frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the ox frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the snake frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the dragon frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the tiger frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the rabbit frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the monkey frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the horse frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the boar frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},
    "year of the sheep frame": {"market": 2, "liquid cost": 1, "type": "Zodiac"},

    # ✦ Carousel ✦
    "wild waters frame": {"market": 45, "liquid cost": 35, "type": "Carousel"},
    "higasa frame": {"market": 55, "liquid cost": 41, "type": "Carousel"},
    "glory frame": {"market": 50, "liquid cost": 36, "type": "Carousel"},
    "rainforest frame": {"market": 50, "liquid cost": 35, "type": "Carousel"},
    "explosion frame": {"market": 50, "liquid cost": 35, "type": "Carousel"},
    "rainbow galaxy": {"market": 35, "liquid cost": 25, "type": "Carousel"},
    "carrara marble frame": {"market": 45, "liquid cost": 35, "type": "Carousel"},
    "starry sky frame": {"market": 50, "liquid cost": 37, "type": "Carousel"},
    "holy roman frame": {"market": 38, "liquid cost": 33, "type": "Carousel"},
    "holy knight frame": {"market": 39, "liquid cost": 31, "type": "Carousel"},
    "gothic tower frame": {"market": 30, "liquid cost": 20, "type": "Carousel"},
    "brawler frame": {"market": 26, "liquid cost": 20, "type": "Carousel"},
    "royal princess frame": {"market": 55, "liquid cost": 45, "type": "Carousel"},
    "yin and yang frame": {"market": 55, "liquid cost": 50, "type": "Carousel"},
    "fire and ice frame": {"market": 55, "liquid cost": 40, "type": "Carousel"},
    "life and death frame": {"market": 25, "liquid cost": 17, "type": "Carousel"},
    "fire element frame": {"market": 30, "liquid cost": 20, "type": "Carousel"},
    "saloon brawl frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "nimbus cloud frame": {"market": 45, "liquid cost": 40, "type": "Carousel"},
    "sakura snack frame": {"market": 55, "liquid cost": 45, "type": "Carousel"},
    "strawberry dessert frame": {"market": 50, "liquid cost": 40, "type": "Carousel"},
    "desert rose frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "sushi buffet frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "simulation frame": {"market": 50, "liquid cost": 35, "type": "Carousel"},
    "noxious frame": {"market": 45, "liquid cost": 30, "type": "Carousel"},
    "Cat Café frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "japanese alley frame": {"market": 45, "liquid cost": 35, "type": "Carousel"},
    "coffee shop frame": {"market": 50, "liquid cost": 30, "type": "Carousel"},
    "chess frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "chefs kitchen frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "moon kingdom frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "magitor frame": {"market": 50, "liquid cost": 35, "type": "Carousel"},
    "mahou frame": {"market": 40, "liquid cost": 25, "type": "Carousel"},
    "stained glass frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "stage showman frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "prison break frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "wanted frame": {"market": 55, "liquid cost": 42, "type": "Carousel"},
    "butler frame": {"market": 45, "liquid cost": 36, "type": "Carousel"},
    "kimono frame": {"market": 50, "liquid cost": 40, "type": "Carousel"},
    "mad tea party frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "classroom frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "bookworm frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "her bedroom frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "jamboree frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "white tiara frame": {"market": 25, "liquid cost": 15, "type": "Carousel"},
    "black tiara frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "dark iron frame": {"market": 30, "liquid cost": 18, "type": "Carousel"},
    "dragon balls frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "aztec jungle frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "garden snake frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "serpent temple frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "bridesmaid frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "groomsman frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "frostborn frame": {"market": 50, "liquid cost": 36, "type": "Carousel"},
    "arcade machine frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "jewelry box frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "jurassic frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "rabbit hole frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "vizier frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "rusty fortress frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "vaporwave frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "volleyball frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "poolside frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "molten frame": {"market": 50, "liquid cost": 35, "type": "Carousel"},
    "panda frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "slums frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "frosted glass frame": {"market": 50, "liquid cost": 36, "type": "Carousel"},
    "mobile suit frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "stacked deck frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "kintsugi frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "astrolabe frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "constellations frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "witch altar frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "geode frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "tarot card frame": {"market": 55, "liquid cost": 35, "type": "Carousel"},
    "tatami frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "tetsuo frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "casino frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "case files frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "hannya frame": {"market": 40, "liquid cost": 28, "type": "Carousel"},
    "starter town frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "archangel frame": {"market": 25, "liquid cost": 15, "type": "Carousel"},
    "electrocell frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "nightmare frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "pastel castle frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "exotic birds frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "alchemist frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "origami frame": {"market": 25, "liquid cost": 15, "type": "Carousel"},
    "gothic ornament frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "petals frame": {"market": 55, "liquid cost": 35, "type": "Carousel"},
    "corrupted titanium frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "heraldic frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "leather belt frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "samurai frame": {"market": 50, "liquid cost": 36, "type": "Carousel"},
    "crime scene frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "tomb relic frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "blueprint frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},
    "shining diamond frame": {"market": 40, "liquid cost": 28, "type": "Carousel"},
    "grove druid frame": {"market": 0, "liquid cost": 0, "type": "Carousel"},

    # ✦ Event - Spring ✦
    "rustic springtide frame": {"market": 3, "liquid cost": 2, "type": "Event - Spring"},
    "ostara frame": {"market": 9, "liquid cost": 6, "type": "Event - Spring"},
    "spring crafts frame": {"market": 15, "liquid cost": 8, "type": "Event - Spring"},
    "springtide treats frame": {"market": 3, "liquid cost": 2, "type": "Event - Spring"},
    "springtide vibes frame": {"market": 5, "liquid cost": 2, "type": "Event - Spring"},
    "bunny paws frame": {"market": 40, "liquid cost": 25, "type": "Event - Spring"},
    "spring lilies frame": {"market": 25, "liquid cost": 18, "type": "Event - Spring"},
    "chocolate bunny frame": {"market": 3, "liquid cost": 2, "type": "Event - Spring"},
    "springtide timber frame": {"market": 3, "liquid cost": 2, "type": "Event - Spring"},
    "spring hatchling frame": {"market": 4, "liquid cost": 2, "type": "Event - Spring"},
    "tranquil blossom frame": {"market": 60, "liquid cost": 40, "type": "Event - Spring"},
    "spring breeze frame": {"market": 65, "liquid cost": 50, "type": "Event - Spring"},
    "rose knight frame": {"market": 45, "liquid cost": 35, "type": "Event - Spring"},
    "enchanted garden frame": {"market": 4, "liquid cost": 2, "type": "Event - Spring"},
    "spring glimmer frame": {"market": 3, "liquid cost": 2, "type": "Event - Spring"},
    "midnight bloom frame": {"market": 25, "liquid cost": 18, "type": "Event - Spring"},
    "spring whimsy frame": {"market": 5, "liquid cost": 2, "type": "Event - Spring"},
    "flowerbuds frame": {"market": 65, "liquid cost": 50, "type": "Event - Spring"},
    "spring rain frame": {"market": 10, "liquid cost": 6, "type": "Event - Spring"},
    "springtide serenity frame": {"market": 45, "liquid cost": 30, "type": "Event - Spring"},
    "elven blossom frame": {"market": 45, "liquid cost": 30, "type": "Event - Spring"},
    "sheep puff frame": {"market": 5, "liquid cost": 2, "type": "Event - Spring"},
    "bunny bliss frame": {"market": 5, "liquid cost": 2, "type": "Event - Spring"},
    "valley elegance frame": {"market": 3, "liquid cost": 2, "type": "Event - Spring"},
    "midnight petal frame": {"market": 25, "liquid cost": 18, "type": "Event - Spring"},
    "moonlit bloom frame": {"market": 25, "liquid cost": 18, "type": "Event - Spring"},
    "luminous wings frame": {"market": 25, "liquid cost": 18, "type": "Event - Spring"},
    "fragrant bloom frame": {"market": 25, "liquid cost": 18, "type": "Event - Spring"},
    "golden nectar frame": {"market": 5, "liquid cost": 2, "type": "Event - Spring"},
    "chocolate drizzle frame": {"market": 2, "liquid cost": 1, "type": "Event - Spring"},

    # ✦ Event - Summer ✦
    "park picnic frame": {"market": 15, "liquid cost": 8, "type": "Event - Summer"},
    "island luau frame": {"market": 4, "liquid cost": 2, "type": "Event - Summer"},
    "beach towel frame": {"market": 4, "liquid cost": 2, "type": "Event - Summer"},
    "ice cream parlor frame": {"market": 10, "liquid cost": 6, "type": "Event - Summer"},
    "solisfair sip frame": {"market": 25, "liquid cost": 18, "type": "Event - Summer"},
    "tropical flame frame": {"market": 20, "liquid cost": 12, "type": "Event - Summer"},
    "solisfair stand frame": {"market": 3, "liquid cost": 1, "type": "Event - Summer"},
    "summer splash frame": {"market": 30, "liquid cost": 22, "type": "Event - Summer"},
    "island grotto frame": {"market": 3, "liquid cost": 2, "type": "Event - Summer"},
    "night festival frame": {"market": 35, "liquid cost": 20, "type": "Event - Summer"},
    "apollo frame": {"market": 30, "liquid cost": 18, "type": "Event - Summer"},
    "oceanic frame": {"market": 5, "liquid cost": 2, "type": "Event - Summer"},
    "lifeguard frame": {"market": 5, "liquid cost": 2, "type": "Event - Summer"},
    "suncatcher frame": {"market": 30, "liquid cost": 20, "type": "Event - Summer"},
    "ripple frame": {"market": 42, "liquid cost": 35, "type": "Event - Summer"},
    "fishing trip frame": {"market": 3, "liquid cost": 2, "type": "Event - Summer"},
    "solisfair swirl frame": {"market": 15, "liquid cost": 8, "type": "Event - Summer"},
    "macaw chief frame": {"market": 3, "liquid cost": 2, "type": "Event - Summer"},
    "warm rain frame": {"market": 25, "liquid cost": 15, "type": "Event - Summer"},
    "karuta vice frame": {"market": 5, "liquid cost": 2, "type": "Event - Summer"},

    # ✦ Event - Halloween ✦
    "halloween porch frame": {"market": 30, "liquid cost": 22, "type": "Event - Halloween"},
    "orb weaver frame": {"market": 32, "liquid cost": 22, "type": "Event - Halloween"},
    "haunted cemetery frame": {"market": 30, "liquid cost": 22, "type": "Event - Halloween"},
    "mad scientist frame": {"market": 20, "liquid cost": 10, "type": "Event - Halloween"},
    "bone construct frame": {"market": 18, "liquid cost": 10, "type": "Event - Halloween"},
    "cursed place frame": {"market": 18, "liquid cost": 10, "type": "Event - Halloween"},
    "witchs broom frame": {"market": 8, "liquid cost": 4, "type": "Event - Halloween"},
    "tpd frame": {"market": 7, "liquid cost": 4, "type": "Event - Halloween"},
    "living dead frame": {"market": 5, "liquid cost": 3, "type": "Event - Halloween"},
    "pumpkin king frame": {"market": 9, "liquid cost": 6, "type": "Event - Halloween"},
    "sealed graveyard frame": {"market": 45, "liquid cost": 30, "type": "Event - Halloween"},
    "monsterific frame": {"market": 10, "liquid cost": 6, "type": "Event - Halloween"},
    "caged essence frame": {"market": 13, "liquid cost": 8, "type": "Event - Halloween"},
    "witchs brew frame": {"market": 5, "liquid cost": 3, "type": "Event - Halloween"},
    "boneslasher frame": {"market": 35, "liquid cost": 25, "type": "Event - Halloween"},
    "undead domain frame": {"market": 9, "liquid cost": 6, "type": "Event - Halloween"},
    "bloodmoon bite frame": {"market": 45, "liquid cost": 30, "type": "Event - Halloween"},
    "gothic cloak frame": {"market": 15, "liquid cost": 8, "type": "Event - Halloween"},
    "spider queen frame": {"market": 80, "liquid cost": 65, "type": "Event - Halloween"},
    "nightwalker frame": {"market": 20, "liquid cost": 10, "type": "Event - Halloween"},
    "phantoms lament frame": {"market": 20, "liquid cost": 10, "type": "Event - Halloween"},
    "black widow frame": {"market": 5, "liquid cost": 3, "type": "Event - Halloween"},
    "cursed relics frame": {"market": 20, "liquid cost": 10, "type": "Event - Halloween"},
    "haunted harvest frame": {"market": 5, "liquid cost": 3, "type": "Event - Halloween"},
    "eldritch frame": {"market": 20, "liquid cost": 12, "type": "Event - Halloween"},
    "grasping shadows frame": {"market": 10, "liquid cost": 6, "type": "Event - Halloween"},
    "silent burial frame": {"market": 20, "liquid cost": 10, "type": "Event - Halloween"},
    "haunted thicket frame": {"market": 20, "liquid cost": 10, "type": "Event - Halloween"},
    "sinister reach frame": {"market": 30, "liquid cost": 17, "type": "Event - Halloween"},
    "magic library frame": {"market": 5, "liquid cost": 2, "type": "Event - Halloween"},

    # ✦ Event - Festivus ✦
    "snow tree frame": {"market": 40, "liquid cost": 22, "type": "Event - Festivus"},
    "mistletoe season frame": {"market": 32, "liquid cost": 20, "type": "Event - Festivus"},
    "nutcracker frame": {"market": 10, "liquid cost": 6, "type": "Event - Festivus"},
    "festivus presents frame": {"market": 20, "liquid cost": 10, "type": "Event - Festivus"},
    "winter campfire frame": {"market": 45, "liquid cost": 30, "type": "Event - Festivus"},
    "festivus park frame": {"market": 15, "liquid cost": 8, "type": "Event - Festivus"},
    "festivus freeze frame": {"market": 80, "liquid cost": 65, "type": "Event - Festivus"},
    "festive dinner frame": {"market": 4, "liquid cost": 2, "type": "Event - Festivus"},
    "festivus night frame": {"market": 18, "liquid cost": 10, "type": "Event - Festivus"},
    "present time frame": {"market": 43, "liquid cost": 22, "type": "Event - Festivus"},
    "snowdrop frame": {"market": 25, "liquid cost": 10, "type": "Event - Festivus"},
    "festivus lights frame": {"market": 5, "liquid cost": 3, "type": "Event - Festivus"},
    "snowed in frame": {"market": 4, "liquid cost": 2, "type": "Event - Festivus"},
    "ornamental frame": {"market": 8, "liquid cost": 5, "type": "Event - Festivus"},
    "wrapped frame": {"market": 8, "liquid cost": 5, "type": "Event - Festivus"},
    "peppermint frame": {"market": 30, "liquid cost": 21, "type": "Event - Festivus"},
    "frostwood frame": {"market": 4, "liquid cost": 2, "type": "Event - Festivus"},
    "shortbread frame": {"market": 10, "liquid cost": 0, "type": "Event - Festivus"},
    "icicle frame": {"market": 80, "liquid cost": 70, "type": "Event - Festivus"},
    "snow day frame": {"market": 5, "liquid cost": 2, "type": "Event - Festivus"},
    "festivity frame": {"market": 10, "liquid cost": 4, "type": "Event - Festivus"},
    "gingerbake frame": {"market": 2, "liquid cost": 1, "type": "Event - Festivus"},
    "snowfire frame": {"market": 16, "liquid cost": 10, "type": "Event - Festivus"},
    "chocomint frame": {"market": 3, "liquid cost": 2, "type": "Event - Festivus"},
    "jingle bells frame": {"market": 2, "liquid cost": 1, "type": "Event - Festivus"},
    "boreal sparkles frame": {"market": 10, "liquid cost": 7, "type": "Event - Festivus"},
    "crisp wind frame": {"market": 40, "liquid cost": 25, "type": "Event - Festivus"},
    "enchanted star frame": {"market": 15, "liquid cost": 8, "type": "Event - Festivus"},
    "runic frost frame": {"market": 25, "liquid cost": 15, "type": "Event - Festivus"},
    "warm mantle frame": {"market": 4, "liquid cost": 2, "type": "Event - Festivus"},

    # ✦ Event - Valentines ✦
    "cupids lock frame": {"market": 15, "liquid cost": 8, "type": "Event - Valentines"},
    "cupids arrow frame": {"market": 15, "liquid cost": 8, "type": "Event - Valentines"},
    "polished locket frame": {"market": 18, "liquid cost": 11, "type": "Event - Valentines"},
    "crystalline locket frame": {"market": 18, "liquid cost": 11, "type": "Event - Valentines"},
    "sweetheart frame": {"market": 80, "liquid cost": 65, "type": "Event - Valentines"},
    "heartbreak frame": {"market": 50, "liquid cost": 35, "type": "Event - Valentines"},
    "wife frame": {"market": 75, "liquid cost": 60, "type": "Event - Valentines"},
    "husband frame": {"market": 40, "liquid cost": 25, "type": "Event - Valentines"},
    "primrose frame": {"market": 30, "liquid cost": 20, "type": "Event - Valentines"},
    "grimrose frame": {"market": 40, "liquid cost": 35, "type": "Event - Valentines"},
    "sanguine wisps frame": {"market": 16, "liquid cost": 9, "type": "Event - Valentines"},
    "pastel wisps frame": {"market": 18, "liquid cost": 10, "type": "Event - Valentines"},

    # ✦ Anniversary ✦
    "karuta anniversary 2021 frame": {"market": 15, "liquid cost": 10, "type": "Anniversary"},
    "karuta anniversary 2022 frame": {"market": 15, "liquid cost": 10, "type": "Anniversary"},
    "karuta anniversary 2023 frame": {"market": 9, "liquid cost": 6, "type": "Anniversary"},
    "karuta anniversary 2024 frame": {"market": 3, "liquid cost": 2, "type": "Anniversary"},
    "karuta anniversary 2025 frame": {"market": 3, "liquid cost": 2, "type": "Anniversary"},
    "karuta anniversary 2026 frame": {"market": 15, "liquid cost": 10, "type": "Anniversary"},

    # ✦ Bits ✦
    "brass frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "fortress frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "beachside frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "volcanic frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "cherry blossom frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "spirit flame frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "night crow frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "crystal mines frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "submarine frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "pirate voyage frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "kominka frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "magus frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "magitek frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "snowlands frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "ice cream sundae frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "dragon hunt frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "patchwork frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "venice carnival frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "robotic frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "frills frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "fuselage frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "rozen frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "smithy forge frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "watermelon juice frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "faerie forest frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "autumn view frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "edo furin frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "barbecue frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "whirlpool frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "bubble bath frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "spaceship frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "wild west frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "archery frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "tree frog frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "scimitar fight frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "bamboo stalks frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "chocolate orange frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "tribal chief frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "abandoned church frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "long hair frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "water element frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "carved stone frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "beauty frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "carnations frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "baroque frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "musical notes frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "winners podium frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "manticore frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "tipsy frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "nordic frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "shiba inu frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "toy mecha frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "bubble tea frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "morning dew frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "nurses office frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "honeycomb frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "magical girl frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "tetromino frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "flying dragon frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "gaming chair frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "tanglung frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "pastel geometry frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "lighthouse storm frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "chopsticks frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "haunted stone frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "kawaii bento frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "pocket pet frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "jade cherrywood frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "pharaoh frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "shisa frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "butterfly garden frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "labpunk frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "wizards hut frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "flame temple frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "night ooze frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "prehistoric frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "kraken frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "bewitched parchment frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "malice tree frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "reclaimed by nature frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "cherry berry frame": {"market": 3, "liquid cost": 2, "type": "Bits"},
    "seamster frame": {"market": 3, "liquid cost": 2, "type": "Bits"}
}